plugins {
    `java-library`
    id("com.github.johnrengelman.shadow") version "8.1.0"
    id("xyz.jpenilla.run-paper") version "2.0.0"
    id("nebula.release") version "17.1.0"
}

group = "com.hackclub.hccore"
//version = autogenerated: use gradle final to bump version
description = "Main plugin for the Hack Club Minecraft server."

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

dependencies {
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("com.slack.api:bolt:1.38.3")
    implementation("com.slack.api:bolt-servlet:1.38.3")
    implementation("com.slack.api:bolt-jetty:1.38.3")
    implementation("javax.websocket:javax.websocket-api:1.1")
    implementation("org.glassfish.tyrus.bundles:tyrus-standalone-client:1.19")
    implementation("org.slf4j:slf4j-simple:2.0.5")
    implementation("org.apache.commons:commons-text:1.11.0")
    implementation("org.apache.commons:commons-collections4:4.4")

    compileOnly("com.frengor:ultimateadvancementapi:2.2.3")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    compileOnly("com.mojang:brigadier:1.0.18")
}

tasks {
    // Run shadowJar on build
    build {
        dependsOn(shadowJar)
    }

    compileJava {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
        // show deprecation warnings: paper deprecated lots of pure string functions for chat components
//      options.isDeprecation = true
    }

    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }

    processResources {
        filteringCharset = Charsets.UTF_8.name()
        expand("name" to rootProject.name, "version" to version)
    }

    shadowJar {
        archiveBaseName.set("HCCore-Shadow")
        archiveClassifier.set("")
    }


    runServer {
        minecraftVersion("1.21.10")
        systemProperty("net.kyori.adventure.text.warnWhenLegacyFormattingDetected", false)
    }
}

repositories {
    mavenCentral()

    // UltimateAdvancementAPI
    maven("https://nexus.frengor.com/repository/public/")

    // NBT-API
    maven("https://repo.codemc.org/repository/maven-public/")

    // Papermc
    maven("https://repo.papermc.io/repository/maven-public/")

    // brigadier
    maven("https://libraries.minecraft.net")
}
