name: ${name}
version: ${version}
api-version: 1.19
main: com.hackclub.hccore.HCCorePlugin
depend:
  - UltimateAdvancementAPI
  - ProtocolLib
commands:
  afk:
    description: Toggles your AFK status
    usage: /afk
    aliases: [ a, away ]
  color:
    description: Sets your chat or name color
    usage: /color <chat|name> [color]
  loc:
    description: Manage your saved locations
    usage: /loc <del|get|list|rename|save|share> [...args]
  nick:
    description: Sets your nickname
    usage: /nick [nickname]
  ping:
    description: Gets the ping of you or a specified player
    usage: /ping [player]
  spawn:
    description: Teleports you to the world’s spawn location
    usage: /spawn
  stats:
    description: Gets the stats of you or a specified player
    usage: /stats [player] [extended|only] <statistic>
  #downvote:
  #  description: Appends a downvote to your message
  #  usage: /downvote [message]
  #shrug:
  #  description: Shrug, just like /shrug in Slack
  #  usage: /shrug [message]
  #tableflip:
  #  description: Appends a tableflip to your message
  #  usage: /tableflip [message]
  #upvote:
  #  description: Appends an upvote to your message
  #  usage: /upvote [message]
  #angry:
  #  description: Appends a angry face to your message
  #  usage: /angry [message]
  #flippedbytable:
  #  description: Appends ノ┬─┬ノ ︵ (/o°o)/  to your message
  #  usage: /flippedbytable [message]
