name: ${project.name}
version: ${project.version}
api-version: 1.15
main: com.hackclub.hccore.HCCorePlugin
depend: [ProtocolLib]
commands:
  afk:
    description: Toggles your AFK status
    usage: /afk
    aliases: [a, away]
  color:
    description: Sets your chat or name color
    usage: /color <chat|name> [color]
  loc:
    description: Manage your saved locations
    usage: /loc <del|get|list|save|share> [...args]
  nick:
    description: Set your nickname
    usage: /nick [nickname]
  ping:
    description: Gets the ping of you or a specified player
    usage: /ping [player]
  shrug:
    description: Shrug, just like /shrug in Slack
    usage: /shrug [message]
  spawn:
    description: Teleports you to the world’s spawn location
    usage: /spawn
  stats:
    description: Gets the stats of you or a specified player
    usage: /stats [player]
