name: ${name}
version: ${version}
api-version: 1.16
main: com.hackclub.hccore.HCCorePlugin
depend: [ProtocolLib]
commands:
  afk:
    description: Toggles your AFK status
    usage: /afk
    aliases: [a, away]
  color:
    description: Sets your chat or name color
    usage: /color <chat|name> [color]
  downvote:
    description: Appends a downvote to your message
    usage: /downvote [message]
  loc:
    description: Manage your saved locations
    usage: /loc <del|get|list|rename|save|share> [...args]
  nick:
    description: Sets your nickname
    usage: /nick [nickname]
  ping:
    description: Gets the ping of you or a specified player
    usage: /ping [player]
  shrug:
    description: Shrug, just like /shrug in Slack
    usage: /shrug [message]
  spawn:
    description: Teleports you to the world’s spawn location
    usage: /spawn
  stats:
    description: Gets the stats of you or a specified player
    usage: /stats [player] [extended|only] <statistic>
  tableflip:
    description: Appends a tableflip to your message
    usage: /tableflip [message]
  upvote:
    description: Appends an upvote to your message
    usage: /upvote [message]
  discord:
    description: Gets the invite link to the Hackclub Minecraft Community Discord server
    usage: /discord
  tutorial:
    description: Greets new users to the server
    usage: /tutorial
